package narino;
import java.util.Date;
public final class AX_SalesTable extends imulik.base.BaseObjectWithChilds
{
	public Date MODIFIEDDATETIME;
	public String Salestyp;
	public String DLVDATE;
	public long RECID;
	public long PARTITION;
	public String RECVERSION;
	public String DATAAREAID;
	public String CREATEDBY;
	public String CREATEDDATETIME;
	public String MODIFIEDBY;
	public String DIRECTBOOKING;
	public String BILLINGPREFIX;
	public String SHIPPINGPREFIX;
	public String EMAILSTATUS;
	public String INVOICEID;
	public String DLVMODE;
	public String DLVTERM;
	public String CUSTACCOUNT;
	public String CREATEDDATETIMEEXTTZID;
	public String CREATEDDATETIMEEXT;
	public String BILLINGCOMPANYNAME;
	public String SHIPPINGCOMPANYNAME;
	public String BILLINGEMAIL;
	public String SHIPPINGEMAIL;
	public String BILLINGCOUNTRYNAME;
	public String SHIPPINGCOUNTRYNAME;
	public String BILLINGPHONE;
	public String SHIPPINGPHONE;
	public String FIRSTNAME;
	public String SHIPPINGLASTNAME;
	public String BILLINGFIRSTNAME;
	public String BILLINGLASTNAME;
	public String BILLINGSTREET;
	public String BILLINGZIPCODE;
	public String BILLINGCITY;
	public String CREDITCARDNOYES;
	public double TAXAMOUNTCUR;
	public double SHIPPINGAMOUNTCUR;
	public double DISCOUNTAMOUNTCUR;
	public double TOTALAMOUNTCUR;
	public String KEYVALUEEXTERNAL;
	public String SHIPPINGSTREET;
	public String SHIPPINGCITY;
	public String SHIPPINGZIPCODE;
	public String COUPONCODES;
	public String CUSTOMERNOTES;
	public String LANGUAGEID;
	public String CURRENCYCODE;
	public String LASTNAME;
	public String SHIPPINGFIRSTNAME;
	public String EMAIL;
	public String SALESID;
	public String SALESIDEXT;
	private static final long serialVersionUID = 1543239320L;
	public static AX_SalesTable getAX_SalesTable(int iPos)throws Exception{return (AX_SalesTable)new AX_SalesTable().getObject(iPos);}
}